// Mock data for recipes
export const recipes = [
  {
    id: 1,
    documentId: "123rwwrwr",
    title: "Avocado Toast",
    author: "Jane Doe",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Breakfast",
    likes: 128,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 2,
    documentId: "123eoiuwr",
    title: "Spaghetti Carbonara",
    author: "John Smith",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Dinner",
    likes: 256,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 3,
    documentId: "123e3diods",
    title: "Green Smoothie",
    author: "Alice Johnson",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Drinks",
    likes: 64,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 4,
    documentId: "13e23diods",
    title: "Green Smoothie",
    author: "Alice Johnson",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Drinks",
    likes: 64,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 5,
    documentId: "13e23diods",
    title: "Green Smoothie",
    author: "Alice Johnson",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Drinks",
    likes: 64,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 6,
    documentId: "123dioeeds",
    title: "Green Smoothie",
    author: "Alice Johnson",
    authorAvatar: "/placeholder.svg?height=40&width=40",
    category: "Drinks",
    likes: 64,
    image: "/placeholder.svg?height=200&width=300",
  },
];
