import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { SearchBar } from "@/components/custom/search-bar";
import { Pagination } from "@/components/custom/pagination";

import { Header } from "@/components/custom/header";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto p-4 max-w-6xl">
          <Header />
          <div className="relative mb-6 ">
            <SearchBar />
          </div>
          <main>{children}</main>
         
        </div>
      </body>
    </html>
  );
}
